name: Build and Release macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 准备图标（如有）
      run: |
        cp icons/icon.icns . || echo "No icon file"

    - name: 打包应用
      run: |
        pyinstaller --onefile --windowed --icon=icon.icns main.py

    - name: 上传到 GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
